### ISSUE TITLE
typedef redefinition

### ISSUE THREAD

**Issue by sailorfeng** [activesys/libcstl#10]
环境
Linux ubuntu 3.0.0-15-generic-pae #26-Ubuntu SMP Fri Jan 20 17:07:31 UTC 2012 i686 i686 i386 GNU/Linux
库
libcstl, libev
编译
clang

stack_t 重定义
In file included from src/inc/cstl/cstack.h:35:
src/inc/cstl/cstl_stack_private.h:45:2: error: typedef redefinition with different types ('struct _tagstack' vs 'struct sigaltstack')
}stack_t;
 ^

In file included from src/inc/ev.h:146:
In file included from /usr/include/signal.h:356:
/usr/include/i386-linux-gnu/bits/sigstack.h:55:5: note: previous definition is here
  } stack_t;
    ^

**Comment by activesys** [comment]
重定义的问题，与其他库或者系统库冲突。

**Comment by activesys** [comment]
目前只能够修改结构定义来去掉编译错误，stack_t -> _stack_t等任何不冲突的 
名字。以后改版的时候可能会修改这个问题。
谢谢

于 2012/2/7 15:17, sailorfeng 写道:

**Comment by activesys** [comment]
暂不修改。
