### ISSUE TITLE
容器比较函数与标准stl不符。

### ISSUE THREAD

**Issue by activesys** [activesys/libcstl#25]
stl中当容器保存的类型不同的时候，有编译错误：
[wangbo@centos stl]$ cat test_compare_not_same_type.cc 

```
#include <iostream>
#include <vector>

int main(int argc, char* argv[])
{
    std::vector<int> v1;
    std::vector<void*> v2;
    std::vector<void*> v3;

    std::cout << bool(v2 == v3) << std::endl;
    std::cout << bool(v1 == v2) << std::endl;

    return 0;
}
```

[wangbo@centos stl]$ g++ -g test_compare_not_same_type.cc 
test_compare_not_same_type.cc: In function ‘int main(int, char**)’:
test_compare_not_same_type.cc:12: error: no match for ‘operator==’ in ‘v1 == v2

但是libcstl认为两个包含不同类型的容器不等：
[wangbo@centos stl]$ cat test_compare_not_same_type.c

```
#include <stdio.h>
#include <cstl/cvector.h>

int main(int argc, char* argv[])
{
    vector_t* pvec1 = create_vector(int);
    vector_t* pvec2 = create_vector(double);
    vector_t* pvec3 = create_vector(double);

    vector_init(pvec1);
    vector_init(pvec2);
    vector_init(pvec3);
    printf("%d, %d\n", vector_equal(pvec1, pvec2), vector_equal(pvec2, pvec3));

    return 0;
}
```

[wangbo@centos stl]$ gcc -lcstl test_compare_not_same_type.c
[wangbo@centos stl]$ ./a.out 
0, 1

**Comment by Endle** [comment]
这应该是编译器的局限吧
要是修改一下代码，在这种情况下， vector_equal 函数 返回 false，并且向 stderr 输出一条 warning 呢？或者，直接加一个断言？

**Comment by activesys** [comment]
版本2.2修改了这个bug。
