### ISSUE TITLE
map<char*,void*>类型在查找的时候的返回值问题

### ISSUE THREAD

**Issue by feelsgoodmc** [activesys/libcstl#32]
map<char*,void*>类型在查找的时候，使用pair_second时返回void**，需要使用*(void**)强转一下才能工作，新手可能完全没有头绪,建议返回值改为void*

**Comment by activesys** [comment]
这是需要权衡的问题，如果像map_at这样的函数返回void_的话，就不能够完全模拟stl中[]操作符了，因为[]是可以修改的，但是直接返回void_就失去了对参数的修改的机会了。所以我决定还是返回类型的指针，对于void_类型来说，map_at这样的函数返回的就是void_*
