### ISSUE TITLE
在Mac下进行make时发生stack_t类型重定义

### ISSUE THREAD

**Issue by frankjiang** [activesys/libcstl#39]
其中**stack_t**在Mac的gcc下已有定义。
见 __signaltstack.h_ 中的`typedef _STRUCT_SIGALTSTACK    stack_t;`

libcstl版本：2.3.0
gcc版本：
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin15.2.0
Thread model: posix

Mac OS X 10.11

**Comment by jidzhang** [comment]
是的，有这个问题。作者还没改

**Comment by chinesejie** [comment]
很好解决，把stack_t改名，比如mstack_t即可。 其实只有5个文件需要改， src下面的cstl_stack_private.c跟cstl_stack.c ，cstl下面的cstl_stack_private.h cstl_stack.h 跟cstack.h

**Comment by chinesejie** [comment]
发现还有一个c文件要修改成 mstack_t, 就是cstl_types_builtin.c

**Comment by chinesejie** [comment]
还有cstl_function.c

**Comment by frankjiang** [comment]
@chinesejie 感谢建议，你的方法的确很详细！
虽然这个issue主要是希望向作者反馈这个project的平台兼容问题，不过作者似乎没有继续更新了。
这样其他开发者看到可以根据你的建议fix。
